In [2]:
import torch
import math

In [3]:
new_tensor = torch.empty(2,3)
new_tensor

#torch.empty(shape) gives output of empty location with the values already in the location in your memory

tensor([[1.4013e-45,        nan, 0.0000e+00],
        [1.4013e-45, 4.0638e-44, 0.0000e+00]])

In [4]:
ones = torch.ones(2,3)   #tensor of ones with shape 2,3
zeros = torch.zeros(2,3) #tensor of zeros with shape 2,3

In [5]:
print(ones)
print(zeros)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [7]:
random = torch.rand(2, 3)
print(random)

tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [8]:
torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

#if you generate random value tensors under same manual_seed, the chances are that the values in the tensor will be same

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [9]:
x = torch.empty(2, 2, 3) #what was in the empty memory location
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x) # similar to x shape
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x) # similar to x shape

print(zeros_like_x.shape) # similar zeros
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[1.5663e+29, 4.3495e-41, 1.5663e+29],
         [4.3495e-41, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [3.2206e-41, 7.7052e+31, 7.2148e+22]]])
torch.Size([2, 2, 3])
tensor([[[1.5663e+29, 4.3495e-41, 1.5663e+29],
         [4.3495e-41, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [3.2206e-41, 7.7052e+31, 7.2148e+22]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.2332, 0.4047, 0.2162],
         [0.9927, 0.4128, 0.5938]],

        [[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]]])


In [10]:
#Using torch.tensor() is the most straightforward way to create a tensor if you already have data in a Python tuple or list. As shown above, nesting the collections will result in a multi-dimensional tensor.
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


In [11]:
'''
torch.bool

torch.int8

torch.uint8

torch.int16

torch.int32

torch.int64

torch.half

torch.float

torch.double

torch.bfloat
'''

#tensor data types

'\ntorch.bool\n\ntorch.int8\n\ntorch.uint8\n\ntorch.int16\n\ntorch.int32\n\ntorch.int64\n\ntorch.half\n\ntorch.float\n\ntorch.double\n\ntorch.bfloat\n'

In [12]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [13]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [14]:
a =     torch.ones(4, 3, 2)

b = a * torch.rand(   3, 2) # 3rd & 2nd dims identical to a, dim 1 absent
print(b)

tensor([[[0.6929, 0.1703],
         [0.1384, 0.4759],
         [0.7481, 0.0361]],

        [[0.6929, 0.1703],
         [0.1384, 0.4759],
         [0.7481, 0.0361]],

        [[0.6929, 0.1703],
         [0.1384, 0.4759],
         [0.7481, 0.0361]],

        [[0.6929, 0.1703],
         [0.1384, 0.4759],
         [0.7481, 0.0361]]])


In [15]:
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5)) #Clamps all elements in input into the range [ min, max ]. Letting min_value and max_value be min and max, respectively

Common functions:
tensor([[0.0124, 0.6939, 0.4823, 0.4587],
        [0.1770, 0.3677, 0.8595, 0.0210]])
tensor([[1., 1., -0., -0.],
        [-0., 1., -0., 1.]])
tensor([[ 0.,  0., -1., -1.],
        [-1.,  0., -1.,  0.]])
tensor([[ 0.0124,  0.5000, -0.4823, -0.4587],
        [-0.1770,  0.3677, -0.5000,  0.0210]])


In [16]:
# trigonometric functions and their inverses
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4,math.pi])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)


Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562, 3.1416])
tensor([ 0.0000e+00,  7.0711e-01,  1.0000e+00,  7.0711e-01, -8.7423e-08])
tensor([ 0.0000e+00,  7.8540e-01,  1.5708e+00,  7.8540e-01, -8.7423e-08])


In [17]:
# bitwise operations
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

# comparisons:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(torch.eq(d, e)) # returns a tensor of type bool


Bitwise XOR:
tensor([3, 2, 1])

Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])


In [18]:
# reductions:
print('\nReduction ops:')
print(torch.max(d))        # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d))       # average
print(torch.std(d))        # standard deviation
print(torch.prod(d))       # product of all numbers
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements"


Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])


In [19]:
# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.])         # x unit vector
v2 = torch.tensor([0., 1., 0.])         # y unit vector
m1 = torch.rand(2, 2)                   # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix

print('\nVectors & Matrices:')
print(torch.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.matmul(m1, m2)
print(m3)                  # 3 times m1
print(torch.svd(m3))       # singular value decomposition


Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.9451, 0.2359],
        [0.1979, 0.3327]])
tensor([[2.8352, 0.7076],
        [0.5938, 0.9982]])
torch.return_types.svd(
U=tensor([[-0.9573, -0.2892],
        [-0.2892,  0.9573]]),
S=tensor([3.0431, 0.7919]),
V=tensor([[-0.9483, -0.3174],
        [-0.3174,  0.9483]]))


In [20]:
# altering and copying tensors
a = torch.ones(2, 2)
b = a

a[0][1] = 561  # we change a...
print(b)

tensor([[  1., 561.],
        [  1.,   1.]])


In [21]:
#cloning
a = torch.ones(2, 2)
b = a.clone()

assert b is not a      # different objects in memory...
print(torch.eq(a, b))  # ...but still with the same contents!

a[0][1] = 561          # a changes...
print(b)               # ...but b is still all ones

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


In [22]:
'''One of the major advantages of PyTorch is its robust acceleration on CUDA-compatible Nvidia GPUs.
  (“CUDA” stands for Compute Unified Device Architecture,
  which is Nvidia’s platform for parallel computing.) So far, everything we’ve done has been on CPU.'''

if torch.cuda.is_available():
    print('We have a GPU!')
else:
    print('Sorry, CPU only.')

We have a GPU!


In [23]:
''' One case where you might need to change the number of dimensions is passing a single instance of input to your model.
 PyTorch models generally expect batches of input.'''

''' For example, imagine having a model that works on 3 x 226 x 226 images - a 226-pixel square with 3 color channels. When you load and transform it, you’ll get a tensor of shape (3, 226, 226).
  Your model, though, is expecting input of shape (N, 3, 226, 226),
  where N is the number of images in the batch. So how do you make a batch of one? '''

a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

'''The unsqueeze() method adds a dimension of extent 1. unsqueeze(0) adds it as a new zeroth dimension - now you have a batch of one!'''


torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [24]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
tensor([[0.9574, 0.4265, 0.5256, 0.9091, 0.2780, 0.2162, 0.9831, 0.8699, 0.2427,
         0.2078, 0.7600, 0.9164, 0.7021, 0.0459, 0.6895, 0.2177, 0.6973, 0.8097,
         0.9646, 0.1726]])
torch.Size([20])
tensor([0.9574, 0.4265, 0.5256, 0.9091, 0.2780, 0.2162, 0.9831, 0.8699, 0.2427,
        0.2078, 0.7600, 0.9164, 0.7021, 0.0459, 0.6895, 0.2177, 0.6973, 0.8097,
        0.9646, 0.1726])
torch.Size([2, 2])
torch.Size([2, 2])


In [25]:
a = torch.ones(4, 3, 2)
b = torch.rand(   3)     # trying to multiply a * b will give a runtime error
print(a * b)

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

In [26]:
a = torch.ones(4, 3, 2)
b = torch.rand(   3)     # trying to multiply a * b will give a runtime error
c = b.unsqueeze(1)       # change to a 2-dimensional tensor, adding new dim at the end
print(c.shape)
print(a * c)

torch.Size([3, 1])
tensor([[[0.5258, 0.5258],
         [0.5329, 0.5329],
         [0.5899, 0.5899]],

        [[0.5258, 0.5258],
         [0.5329, 0.5329],
         [0.5899, 0.5899]],

        [[0.5258, 0.5258],
         [0.5329, 0.5329],
         [0.5899, 0.5899]],

        [[0.5258, 0.5258],
         [0.5329, 0.5329],
         [0.5899, 0.5899]]])


### ADVISED TO WATCH TO GRAB A CLEARER CONCEPT

[A Discussion on "AUTOGRAD"]("https://youtu.be/MswxJw-8PvE?si=WwVHmUxups6230BX")